name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  release:
    types: [ "published" ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Build With Maven
        run: mvn -B package --file pom.xml

  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: github.event_name == 'release'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          java-version: 17
          distribution: temurin
          cache: maven

      - name: Get version from release tag
        run: |
          TAG=${{ github.event.release.tag_name }}
          echo "VERSION=${TAG#v}" >> $GITHUB_OUTPUT
        id: version

      - name: Set version from release tag
        run: mvn -B versions:set -DnewVersion=${{ steps.version.outputs.VERSION }} -DgenerateBackupPoms=false

      - name: Build and package Maven project
        run: mvn -B clean package --file pom.xml

      - name: Upload to release
        uses: cloudnode-pro/release-upload-asset@v1
        with:
          gh-token: ${{ github.token }}
          files: target/AnvilUnlocker-${{ steps.version.outputs.VERSION }}.jar; type=application/java-archive

      - name: Upload to Modrinth
        uses: cloudnode-pro/modrinth-publish@v2
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: ${{ github.event.repository.custom_properties.modrinth_id }}
          name: ${{ github.event.release.name == github.event.release.tag_name && format('AnvilUnlocker {0}', github.event.release.name) || github.event.release.name }}
          version: ${{ steps.version.outputs.VERSION }}
          changelog: ${{ github.event.release.body }}
          loaders: |-
            paper
            bukkit
            spigot
          game-versions: ">=1.15"
          files: target/AnvilUnlocker-${{ steps.version.outputs.VERSION }}.jar
